[package]
name = "todos-inquire"
version = "0.1.0"
edition = "2021"

[dev-dependencies]
pretty_assertions = "1"

[dependencies]
inquire = "0.7.5"
serde = { version = "1.0.219", features = [ "derive" ] }
serde_json = "1.0"
